apiVersion: apps/v1
kind: Deployment
metadata:
  name: seraphim-inference
  labels:
    app: seraphim-inference
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: seraphim-inference
  template:
    metadata:
      labels:
        app: seraphim-inference
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
{{- if .Values.env }}
{{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
{{- end }}
{{- end }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
{{- toYaml .Values.resources | nindent 12 }}
