apiVersion: v1
kind: Service
metadata:
  name: seraphim-inference
spec:
  type: {{ .Values.service.type }}
  selector:
    app: seraphim-inference
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
      