services:
  model-server:
    build:
      context: ./services/model-server
      platforms:
        - linux/amd64
    image: seraphim-model-server:dev
    platform: linux/amd64
    environment:
      SAMPLE_MODEL: "true"
      SAMPLE_MODEL_VERSIONS: "1.0,2.0"
    ports:
      - "9080:8080"
      - "9081:8081"
      - "9082:8082"

  inference:
    build:
      context: ./services/inference
    image: seraphim-inference:dev
    environment:
      TS_URL: http://model-server:8080
      MODEL_NAME_BASELINE: custom-text
      MODEL_VERSION_BASELINE: "1.0"
      MODEL_NAME_CANDIDATE: custom-text
      MODEL_VERSION_CANDIDATE: "2.0"
      CANARY_PERCENT: "10"
      CANARY_STICKY_HEADER: X-User-Id
      CANARY_STICKY_SALT: seraphim
      TS_TIMEOUT_MS: "500"
    ports:
      - "8088:8080"
    depends_on:
      - model-server

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./config/observe/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./config/observe/prometheus/rules.yml:/etc/prometheus/rules.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - inference
      - model-server

  grafana:
    image: grafana/grafana-oss:latest
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    volumes:
      - ./config/observe/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./config/observe/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./config/observe/grafana/dashboards:/etc/grafana/dashboards:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
