image:
  repository: seraphim-inference
  tag: dev
  pullPolicy: IfNotPresent
replicaCount: 1
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
service:
  type: ClusterIP
  port: 80
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
