image:
  repository: seraphim-inference
  tag: prod
  pullPolicy: IfNotPresent
replicaCount: 3
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi
service:
  type: ClusterIP
  port: 80
hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 60

