name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install linters
        run: pip install --upgrade pip && pip install black isort flake8
      - name: Black check
        run: black --check services tests config
      - name: isort check
        run: isort --check-only --profile black services tests config
      - name: flake8
        run: flake8 services tests config
